<?php
include 'connect.php';

$answers = [3, 1, 2, 2, 4, 1, 1, 1, 4, 1]; // Correct answers

$sql = "SELECT * FROM data WHERE UID='3856' ORDER BY id DESC LIMIT 1";
$result = $conn->query($sql);

// Default values
$questions = array_fill(0, 10, 0);

if ($result->num_rows > 0) {
    $row = $result->fetch_assoc();
    $questions = [
        $row["ques1"], $row["ques2"], $row["ques3"], $row["ques4"],
        $row["ques5"], $row["ques6"], $row["ques7"], $row["ques8"],
        $row["ques9"], $row["ques0"]
    ];
}
?>

<html>
<head>
    <title>ECET-MOCKTEST/CHEMISTRY/Test-6/Key-paper</title>
    <link rel="stylesheet" href="satya.css"/>
    <link rel="icon" href="logo.png" type="image/x-icon">
    <style>
        .s { width: 400px; height: 40px; margin-bottom: 10px; }
        .correct { border: 5px solid green; border-radius: 10px; }
        .incorrect { border: 5px solid red; border-radius: 10px; }
        .true-answer { border: 5px solid green; border-radius: 10px; }
    </style>
</head>
<body>
    <center class="textcolor">
        <h1>CHEMISTRY - TEST:6/10</h1>
        <h1>KEY-PAPER</h1>
    </center>

    <ol type="1">
        <?php 
       $questionsData = [
    [
        'One Faraday is equal to:',
        ['99650 C', '93100 C', '96500 C', '94500 C'],
        '96500 C'
    ],
    [
        'The cell reduction of a cell is Mg(s) + 2H⁺(aq) → Mg²⁺(aq) + H₂(g). If the standard reduction potential of Zn is -2.372V, then the emf of the cell is:',
        ['+2.372V', '-2.372V', '0.00V', '-1.372V'],
        '+2.372V'
    ],
    [
        'Galvanic cells are the cells which convert:',
        ['Electrical energy to chemical energy', 'Chemical energy to electrical energy', 'Chemical energy into free energy', 'Potential energy to kinetic energy'],
        'Chemical energy to electrical energy'
    ],
    [
        'Mass of substance produced at electrode is directly proportional to the quantity of electricity passed. This is known as:',
        ['Faraday\'s second law', 'Faraday\'s first law', 'Newton\'s third law', 'Newton\'s first law'],
        'Faraday\'s first law'
    ],
    [
        'Hardness of water is expressed in terms of equivalent of:',
        ['Na₂CO₃', 'K₂CO₃', 'MgCO₃', 'CaCO₃'],
        'CaCO₃'
    ],
    [
        'Temporary hardness is caused by:',
        ['Carbonates of calcium and magnesium', 'Chlorides of calcium and magnesium', 'Sulphates of calcium and magnesium', 'Nitrates of Calcium'],
        'Carbonates of calcium and magnesium'
    ],
    [
        'The exhausted zeolite bed can be regenerated by washing with:',
        ['NaCl', 'dil. NaOH', 'dil. HCl', 'Distilled water'],
        'NaCl'
    ],
    [
        'Corrosion is an example of:',
        ['Oxidation', 'Reduction', 'Electrolysis', 'Halogenation'],
        'Oxidation'
    ],
    [
        'The composition of rust is:',
        ['Fe(OH)₃', 'FeCl₃', 'FeO', 'Fe₂O₃.xH₂O'],
        'Fe₂O₃.xH₂O'
    ],
    [
        'Which one of the following statements is not true?',
        ['Natural rubber has the trans-configuration at every double bond', 'Buna-S is a copolymer of butadiene and styrene', 'Natural rubber is a 1,4-polymer of isoprene', 'In vulcanization, the formation of sulphur bridges between different chains makes rubber harder and stronger'],
        'Natural rubber has the trans-configuration at every double bond'
    ]
];


        foreach ($questionsData as $index => $data) {
            echo "<li>{$data[0]}<br><ol type='A'>";
            foreach ($data[1] as $i => $answer) {
                $class = '';
                $selectedAnswer = $questions[$index];  
                $correctAnswer = array_search($data[2], $data[1]) + 1; // Find the index of the correct answer

                if ($selectedAnswer == ($i + 1)) {
                    if ($selectedAnswer == $correctAnswer) {
                        $class = 'correct'; 
                    } else {
                        $class = 'incorrect'; 
                    }
                } else {
                    if ($i + 1 == $correctAnswer) {
                        $class = 'true-answer'; 
                    }
                }

                echo "<div class='s $class'><input type='radio' disabled checked> $answer</div>";
            }
            echo "</ol></li><br>";
        }
        ?>
    </ol>

    <center><button class="satya" onclick="back()"><< BACK</button></center>
</body>
</html>

<script>
function back() {
    window.location = "che6.php";
}
</script>
